#!/bin/sh

case "${reason}" in
	BOUND|REBIND|REBOOT|RENEW|TIMEOUT|STATIC)
		# send openvpn processes SIGUSR1 and make them reconnect
		if pgrep -x openvpn >/dev/null; then
			kill -USR1 $(pgrep -x openvpn)
		fi
		;;
	PREINIT|EXPIRE|INFORM|FAIL|IPV4LL|NAK|NOCARRIER|RELEASE|STOP)
		# do nothing here...
		;;
esac
